services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=zapisy
    ports: 
      - "5432:5432"
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d
    networks:
      - pg-network
    restart: always

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org 
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_LISTEN_PORT=5555
    ports:
      - "5555:5555"
    restart: always
    depends_on:
      - postgres
    networks:
      - pg-network
    
  app:
    container_name: app 
    build: .
    ports:
      - "9000:9000"
    depends_on:
      - postgres
    networks:
      - pg-network

networks:
  pg-network: